// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/messages/domain/message_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/messages/domain/message_repository.go -destination=internal/mocks/messages/mock_message_repository.go -package=messages
//

// Package messages is a generated GoMock package.
package messages

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/DevanshSharmaT-T/Go-Gin-Template/internal/modules/messages/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationRepository is a mock of NotificationRepository interface.
type MockNotificationRepository struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationRepositoryMockRecorder
	isgomock struct{}
}

// MockNotificationRepositoryMockRecorder is the mock recorder for MockNotificationRepository.
type MockNotificationRepositoryMockRecorder struct {
	mock *MockNotificationRepository
}

// NewMockNotificationRepository creates a new mock instance.
func NewMockNotificationRepository(ctrl *gomock.Controller) *MockNotificationRepository {
	mock := &MockNotificationRepository{ctrl: ctrl}
	mock.recorder = &MockNotificationRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationRepository) EXPECT() *MockNotificationRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockNotificationRepository) Create(ctx context.Context, notification *domain.Notification) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, notification)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockNotificationRepositoryMockRecorder) Create(ctx, notification any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockNotificationRepository)(nil).Create), ctx, notification)
}

// ListForUser mocks base method.
func (m *MockNotificationRepository) ListForUser(ctx context.Context, userID uuid.UUID, page domain.Page) ([]*domain.Notification, int64, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListForUser", ctx, userID, page)
	ret0, _ := ret[0].([]*domain.Notification)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ListForUser indicates an expected call of ListForUser.
func (mr *MockNotificationRepositoryMockRecorder) ListForUser(ctx, userID, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListForUser", reflect.TypeOf((*MockNotificationRepository)(nil).ListForUser), ctx, userID, page)
}

// MarkAllRead mocks base method.
func (m *MockNotificationRepository) MarkAllRead(ctx context.Context, userID uuid.UUID, at time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllRead", ctx, userID, at)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkAllRead indicates an expected call of MarkAllRead.
func (mr *MockNotificationRepositoryMockRecorder) MarkAllRead(ctx, userID, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllRead", reflect.TypeOf((*MockNotificationRepository)(nil).MarkAllRead), ctx, userID, at)
}

// MarkRead mocks base method.
func (m *MockNotificationRepository) MarkRead(ctx context.Context, userID, id uuid.UUID, at time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRead", ctx, userID, id, at)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkRead indicates an expected call of MarkRead.
func (mr *MockNotificationRepositoryMockRecorder) MarkRead(ctx, userID, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRead", reflect.TypeOf((*MockNotificationRepository)(nil).MarkRead), ctx, userID, id, at)
}

// UnreadCount mocks base method.
func (m *MockNotificationRepository) UnreadCount(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnreadCount", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UnreadCount indicates an expected call of UnreadCount.
func (mr *MockNotificationRepositoryMockRecorder) UnreadCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnreadCount", reflect.TypeOf((*MockNotificationRepository)(nil).UnreadCount), ctx, userID)
}

// MockOutboundMailRepository is a mock of OutboundMailRepository interface.
type MockOutboundMailRepository struct {
	ctrl     *gomock.Controller
	recorder *MockOutboundMailRepositoryMockRecorder
	isgomock struct{}
}

// MockOutboundMailRepositoryMockRecorder is the mock recorder for MockOutboundMailRepository.
type MockOutboundMailRepositoryMockRecorder struct {
	mock *MockOutboundMailRepository
}

// NewMockOutboundMailRepository creates a new mock instance.
func NewMockOutboundMailRepository(ctrl *gomock.Controller) *MockOutboundMailRepository {
	mock := &MockOutboundMailRepository{ctrl: ctrl}
	mock.recorder = &MockOutboundMailRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboundMailRepository) EXPECT() *MockOutboundMailRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockOutboundMailRepository) Create(ctx context.Context, record *domain.OutboundMail) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockOutboundMailRepositoryMockRecorder) Create(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockOutboundMailRepository)(nil).Create), ctx, record)
}

// List mocks base method.
func (m *MockOutboundMailRepository) List(ctx context.Context, page domain.Page) ([]*domain.OutboundMail, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page)
	ret0, _ := ret[0].([]*domain.OutboundMail)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockOutboundMailRepositoryMockRecorder) List(ctx, page any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockOutboundMailRepository)(nil).List), ctx, page)
}
