// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/users/domain/verification_token_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/users/domain/verification_token_repository.go -destination=internal/mocks/users/mock_verification_token_repository.go -package=users
//

// Package users is a generated GoMock package.
package users

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/DevanshSharmaT-T/Go-Gin-Template/internal/modules/users/domain"
	crypt "github.com/DevanshSharmaT-T/Go-Gin-Template/internal/shared/crypt"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVerificationTokenRepository is a mock of VerificationTokenRepository interface.
type MockVerificationTokenRepository struct {
	ctrl     *gomock.Controller
	recorder *MockVerificationTokenRepositoryMockRecorder
	isgomock struct{}
}

// MockVerificationTokenRepositoryMockRecorder is the mock recorder for MockVerificationTokenRepository.
type MockVerificationTokenRepositoryMockRecorder struct {
	mock *MockVerificationTokenRepository
}

// NewMockVerificationTokenRepository creates a new mock instance.
func NewMockVerificationTokenRepository(ctrl *gomock.Controller) *MockVerificationTokenRepository {
	mock := &MockVerificationTokenRepository{ctrl: ctrl}
	mock.recorder = &MockVerificationTokenRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerificationTokenRepository) EXPECT() *MockVerificationTokenRepositoryMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockVerificationTokenRepository) Consume(ctx context.Context, id uuid.UUID, at time.Time) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, id, at)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Consume indicates an expected call of Consume.
func (mr *MockVerificationTokenRepositoryMockRecorder) Consume(ctx, id, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Consume), ctx, id, at)
}

// Create mocks base method.
func (m *MockVerificationTokenRepository) Create(ctx context.Context, token *domain.VerificationToken) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockVerificationTokenRepositoryMockRecorder) Create(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockVerificationTokenRepository)(nil).Create), ctx, token)
}

// DeleteExpired mocks base method.
func (m *MockVerificationTokenRepository) DeleteExpired(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpired", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpired indicates an expected call of DeleteExpired.
func (mr *MockVerificationTokenRepositoryMockRecorder) DeleteExpired(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpired", reflect.TypeOf((*MockVerificationTokenRepository)(nil).DeleteExpired), ctx, before)
}

// FindByFingerprint mocks base method.
func (m *MockVerificationTokenRepository) FindByFingerprint(ctx context.Context, fingerprint string) (*domain.VerificationToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFingerprint", ctx, fingerprint)
	ret0, _ := ret[0].(*domain.VerificationToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFingerprint indicates an expected call of FindByFingerprint.
func (mr *MockVerificationTokenRepositoryMockRecorder) FindByFingerprint(ctx, fingerprint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFingerprint", reflect.TypeOf((*MockVerificationTokenRepository)(nil).FindByFingerprint), ctx, fingerprint)
}

// InvalidateOutstanding mocks base method.
func (m *MockVerificationTokenRepository) InvalidateOutstanding(ctx context.Context, userID uuid.UUID, purpose crypt.Purpose, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateOutstanding", ctx, userID, purpose, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateOutstanding indicates an expected call of InvalidateOutstanding.
func (mr *MockVerificationTokenRepositoryMockRecorder) InvalidateOutstanding(ctx, userID, purpose, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateOutstanding", reflect.TypeOf((*MockVerificationTokenRepository)(nil).InvalidateOutstanding), ctx, userID, purpose, at)
}
