// Code generated by MockGen. DO NOT EDIT.
// Source: internal/modules/roles/domain/role_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/modules/roles/domain/role_repository.go -destination=internal/mocks/roles/mock_role_repository.go -package=roles
//

// Package roles is a generated GoMock package.
package roles

import (
	context "context"
	reflect "reflect"

	domain "github.com/DevanshSharmaT-T/Go-Gin-Template/internal/modules/roles/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleRepository is a mock of RoleRepository interface.
type MockRoleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRepositoryMockRecorder
	isgomock struct{}
}

// MockRoleRepositoryMockRecorder is the mock recorder for MockRoleRepository.
type MockRoleRepositoryMockRecorder struct {
	mock *MockRoleRepository
}

// NewMockRoleRepository creates a new mock instance.
func NewMockRoleRepository(ctrl *gomock.Controller) *MockRoleRepository {
	mock := &MockRoleRepository{ctrl: ctrl}
	mock.recorder = &MockRoleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRepository) EXPECT() *MockRoleRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockRoleRepository) GetByID(ctx context.Context, id int64) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleRepository)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockRoleRepository) List(ctx context.Context) ([]*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRoleRepositoryMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleRepository)(nil).List), ctx)
}

// ListPermissions mocks base method.
func (m *MockRoleRepository) ListPermissions(ctx context.Context) ([]*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPermissions", ctx)
	ret0, _ := ret[0].([]*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPermissions indicates an expected call of ListPermissions.
func (mr *MockRoleRepositoryMockRecorder) ListPermissions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPermissions", reflect.TypeOf((*MockRoleRepository)(nil).ListPermissions), ctx)
}

// PermissionsFor mocks base method.
func (m *MockRoleRepository) PermissionsFor(ctx context.Context, roleID int64) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PermissionsFor", ctx, roleID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PermissionsFor indicates an expected call of PermissionsFor.
func (mr *MockRoleRepositoryMockRecorder) PermissionsFor(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PermissionsFor", reflect.TypeOf((*MockRoleRepository)(nil).PermissionsFor), ctx, roleID)
}

// ReplaceGrants mocks base method.
func (m *MockRoleRepository) ReplaceGrants(ctx context.Context, roleID int64, slugs []string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceGrants", ctx, roleID, slugs)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceGrants indicates an expected call of ReplaceGrants.
func (mr *MockRoleRepositoryMockRecorder) ReplaceGrants(ctx, roleID, slugs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceGrants", reflect.TypeOf((*MockRoleRepository)(nil).ReplaceGrants), ctx, roleID, slugs)
}

// Snapshot mocks base method.
func (m *MockRoleRepository) Snapshot(ctx context.Context) (*domain.Snapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", ctx)
	ret0, _ := ret[0].(*domain.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockRoleRepositoryMockRecorder) Snapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockRoleRepository)(nil).Snapshot), ctx)
}

// SuspendedUserIDs mocks base method.
func (m *MockRoleRepository) SuspendedUserIDs(ctx context.Context) ([]uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SuspendedUserIDs", ctx)
	ret0, _ := ret[0].([]uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SuspendedUserIDs indicates an expected call of SuspendedUserIDs.
func (mr *MockRoleRepositoryMockRecorder) SuspendedUserIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SuspendedUserIDs", reflect.TypeOf((*MockRoleRepository)(nil).SuspendedUserIDs), ctx)
}
